name: Release

on:
  push:
    branches:
      - master

permissions:
  contents: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest
    container: ghcr.io/release-engineers/build-image-poetry:latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: master
          fetch-depth: 0
      - uses: release-engineers/build-system@v0
      - shell: bash
        run: |
          git config --global --add safe.directory '*'
          git config --local user.name 'github-actions[bot]'
          git config --local user.email 'github-actions[bot]@users.noreply.github.com'
          build-system increment
          build-system build
          build-system test
      - shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: |
          build-system release
  templating:
    runs-on: ubuntu-latest
    needs: [release]
    steps:
      - uses: actions/checkout@v3
        with:
          ref: master
      - uses: release-engineers/action-template@v2
        with:
          source: 'README.md.template'
          target: 'README.md'
      - shell: bash
        run: |
          git config --global --add safe.directory '*'
          git config --local user.name 'github-actions[bot]'
          git config --local user.email 'github-actions[bot]@users.noreply.github.com'
          git add README.md
          if git commit --no-verify -m "docs: Regenerate README.md"; then
            # rebase and push in a retry loop
            for i in {1..5}; do
              git pull --rebase && git push && break || sleep 1
            done
          fi
