name: Build

on:
  push:
    branches-ignore:
      - master
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
#      - uses: docker/setup-buildx-action@v2
      - shell: bash
        run: |
          docker build --cache-to type=gha --cache-from type=gha --target test .
          docker build --cache-to type=gha --cache-from type=gha --target release_docker .